In [2]:
#1d array 
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
#shape of array 
print("shape",a.shape)

shape (5,)


In [4]:
print("dimension",a.ndim)

dimension 1


In [5]:
print("size",a.size)

size 5


In [6]:
print("data type",a.dtype)

data type int64


In [7]:
print("size of item",a.itemsize)

size of item 8


In [8]:
# create a 2d array with oparation 
b=np.array([[1,2,3],[4,5,6]])
c=np.array([[8,9,10],[11,12,13]])
print(b)
print(c)

[[1 2 3]
 [4 5 6]]
[[ 8  9 10]
 [11 12 13]]


In [10]:
# add a 2 array 
add=np.add(b,c)
print("add:",add)

add: [[ 9 11 13]
 [15 17 19]]


In [11]:
# subtract with 2 array
subtract=np.subtract(b,c)
print("subtract:",subtract)


subtract: [[-7 -7 -7]
 [-7 -7 -7]]


In [12]:
# divide 
divide=np.divide(b,c)
print("divide:",divide)

divide: [[0.125      0.22222222 0.3       ]
 [0.36363636 0.41666667 0.46153846]]


In [13]:
# multiply 
multiply=np.multiply(b,c)
print("multiply:",multiply)

multiply: [[ 8 18 30]
 [44 60 78]]


In [19]:
mod=np.mod(b,c)
print("mod two array:",mod)

mod two array: [[1 2 3]
 [4 5 6]]


In [17]:
remainder=np.remainder(b,c)
print("remainder:",remainder)

remainder: [[1 2 3]
 [4 5 6]]


In [23]:
power=np.power(b,c)
print("power:",power)

power: [[          1         512       59049]
 [    4194304   244140625 13060694016]]


In [24]:
absolute=np.absolute(b)
print("absolute:",absolute)

absolute: [[1 2 3]
 [4 5 6]]


In [27]:
print("sum : ",np.sum(b))
print("sqrt : ",np.sqrt(b))

sum :  21
sqrt :  [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [ ]:
b1=np.array([[1,2],[3,4]])
b2=np.array([[6,8],[11,12]])
mul=np.dot(b1,b2)
print("multiplication: ",mul)
b1*b2
git clone https://github.com/princeprajapati01/numpy_basic.git


multiplication:  [[28 32]
 [62 72]]


array([[ 6, 16],
       [33, 48]])